# Generated by Django 5.1.3 on 2024-12-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nama_admin', models.CharField(max_length=100)),
                ('username_admin', models.CharField(max_length=20, unique=True)),
                ('password_admin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JenisLayanan',
            fields=[
                ('id_jenis_layanan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_layanan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriMobil',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LayananSewa',
            fields=[
                ('id_layanan', models.AutoField(primary_key=True, serialize=False)),
                ('harga_layanan', models.FloatField()),
                ('id_jenis_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layanan', to='waxsik_website.jenislayanan')),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layanan', to='waxsik_website.kategorimobil')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPemesanan',
            fields=[
                ('id_pemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pengerjaan', models.DateField()),
                ('tanggal_pemesanan', models.DateField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemesanan', to='waxsik_website.admin')),
                ('layanan_sewa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemesanan', to='waxsik_website.layanansewa')),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=200)),
                ('nomor_hp', models.CharField(max_length=20)),
                ('layanan_dipesan', models.ManyToManyField(through='waxsik_website.DetailPemesanan', to='waxsik_website.layanansewa')),
            ],
        ),
        migrations.AddField(
            model_name='detailpemesanan',
            name='pelanggan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemesanan', to='waxsik_website.pelanggan'),
        ),
    ]
