# Generated by Django 5.1.3 on 2024-12-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waxsik_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPemesanan',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pelanggan',
            name='layanan_dipesan',
        ),
    ]
